### ISSUE TITLE
Падение приложения при попытке отобразить чат

### ISSUE THREAD

**Issue by b3er** [ThreadsMobileLib/edna-sdk-android#8]
В репортах появилось вот такое падение
К сожалению воспроизвести на тестах не получается, но проблема не единична

Версия библиотеки: 3.6.1

Stacktrace
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
       at android.text.SpannableString.<init>(SpannableString.java:30)
       at im.threads.internal.holders.SystemMessageViewHolder.onBind(SystemMessageViewHolder.java:1)
       at im.threads.internal.adapters.ChatAdapter.bindSystemMessageVH(ChatAdapter.java:1)
       at im.threads.internal.adapters.ChatAdapter.onBindViewHolder(ChatAdapter.java:2)
       at androidx.recyclerview.widget.RecyclerView$g.onBindViewHolder(RecyclerView.java:1)
       at androidx.recyclerview.widget.RecyclerView$g.bindViewHolder(RecyclerView.java:7)
       at androidx.recyclerview.widget.RecyclerView$v.l(RecyclerView.java:6)
       at androidx.recyclerview.widget.RecyclerView$v.m(RecyclerView.java:134)
       at androidx.recyclerview.widget.RecyclerView$v.e(RecyclerView.java:1)
       at androidx.recyclerview.widget.LinearLayoutManager$c.c(LinearLayoutManager.java:8)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:49)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:9)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
       at android.view.View.layout(View.java:17666)
       at android.view.ViewGroup.layout(ViewGroup.java:5577)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2390)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2112)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1298)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6437)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
       at android.view.Choreographer.doCallbacks(Choreographer.java:688)
       at android.view.Choreographer.doFrame(Choreographer.java:623)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6238)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)`

**Comment by b3er** [comment]
UPD: Падает в моменте, когда оператор отсоединяется от чата, в дальнейшем, любая опытка открыть чат приводит к падению
